### ISSUE TITLE
Application fails to start if /tmp mounted with noexec

### ISSUE THREAD

**Issue by hexion** [NyaomiDEV/Sunamu#33]
Steps to reproduce on Linux:

$ sudo mount -o remount,noexec /tmp
[sudo] password for xxxxx: 

$ /opt/Sunamu/Sunamu
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.yDNkdK: failed to map segment from shared object
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/opt/Sunamu/resources/app.asar/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/opt/Sunamu/resources/app.asar/node_modules/leveldown/binding.js:1:43)
[6532:0802/103649.142339:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by NyaomiDEV** [comment]
Ermmmmmmmm............ I am not sure I can fix this. Heck I am not even sure if this is a me problem or a Node / Electron problem.

What do I do?

**Comment by NyaomiDEV** [comment]
Can you try this version? https://transfer.sh/g1Sm4o/sunamu-2.1.0.tar.xz (if you want to build it yourself, you can build `sunamu-git` @ AUR or just clone `master` and build that way)

**Comment by hexion** [comment]
The new version runs fine, the widget loads and there is no stack trace.
+1

**Comment by NyaomiDEV** [comment]
Just do keep in mind it's not final (if you decide to keep running it, which I think you will.)

Closing then.

**Comment by hexion** [comment]
Awesome, thanks for the quick fix!
